#!/usr/bin/env python3
"""Generate src/lib/types/settings.generated.ts from the firmware's kFields table.

The hand-maintained Settings TypeScript shape in
`src/lib/types/settings.ts` doesn't carry bounds, boot-only flags, or
defaults. The firmware does — `kFields` in
`components/settings/include/settings/schema.hpp` is the canonical
table. This script parses that table and emits a sibling TS module
exposing the same metadata, so the WebUI can:

  * tag inputs that flip a `boot_only` field with the "restart required"
    hint without copy-pasting the list,
  * apply min/max ranges to NumberField inputs without the firmware
    rejecting the PATCH after a round-trip,
  * derive defaults that the WebUI's reset-to-defaults button can use.

The script is read-only: it does *not* generate the Settings *type*
itself. That stays hand-maintained because some fields (timePerScreen,
*Set booleans, gitTag/gitRev/lastBuildTime) are emitted by the firmware
but absent from kFields, and squeezing the GET-only fields into the
PATCH-table would conflate two different contracts.

Usage:
    python3 scripts/generate-settings-meta.py [--firmware ..]

The default firmware directory is resolved automatically: if this WebUI
checkout lives inside the firmware tree (`…/btclock_v4/data`), the parent
folder is used; otherwise if a sibling `btclock_v4/` exists (classic
side‑by‑side clone), that path is used. Pass `--firmware` explicitly when
neither matches.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from typing import Iterator


# ---- Parsers ---------------------------------------------------------------

PREF_KEYS_RE = re.compile(
    r'inline constexpr const char\* (?P<sym>k[A-Za-z0-9]+) = "(?P<key>[^"]+)"'
)
KFIELDS_RE = re.compile(
    r"\{\s*prefs::(?P<sym>k[A-Za-z0-9]+),\s*"
    r"FieldKind::(?P<kind>k[A-Za-z]+),\s*"
    r"(?P<boot_only>true|false),\s*"
    r"(?P<min>0x[0-9A-Fa-f]+u?|\d+|\d+\s*\*\s*\d+),\s*"
    r"(?P<max>0x[0-9A-Fa-f]+u?|\d+|\d+\s*\*\s*\d+),\s*"
    r"(?P<default_bool>true|false),\s*"
    r"(?P<default_int>0x[0-9A-Fa-f]+u?|-?\d+|\d+\s*\*\s*\d+),\s*"
    r'(?:"(?P<default_str>[^"]*)"|\{\})'
    r"\s*\}",
    re.MULTILINE,
)

KIND_TO_TS: dict[str, str] = {
    "kString": "string",
    "kUint": "number",
    "kInt": "number",
    "kBool": "boolean",
    "kUChar": "number",
}


def parse_int(raw: str) -> int:
    """Handle `15 * 60`, `0xFF`, decimal."""
    raw = raw.strip().rstrip("u")
    if "*" in raw:
        a, b = (int(x.strip()) for x in raw.split("*"))
        return a * b
    return int(raw, 16) if raw.startswith("0x") else int(raw)


def parse_pref_keys(text: str) -> dict[str, str]:
    return {m.group("sym"): m.group("key") for m in PREF_KEYS_RE.finditer(text)}


def parse_kfields(text: str, key_map: dict[str, str]) -> Iterator[dict]:
    for m in KFIELDS_RE.finditer(text):
        sym = m.group("sym")
        if sym not in key_map:
            sys.exit(f"kFields references unknown prefs::{sym} — pref_keys out of sync?")
        yield {
            "key": key_map[sym],
            "kind": KIND_TO_TS[m.group("kind")],
            "bootOnly": m.group("boot_only") == "true",
            "minValue": parse_int(m.group("min")),
            "maxValue": parse_int(m.group("max")),
            "defaultBool": m.group("default_bool") == "true",
            "defaultInt": parse_int(m.group("default_int")),
            "defaultStr": m.group("default_str") or "",
        }


# ---- Emitter ---------------------------------------------------------------

HEADER = """\
// AUTO-GENERATED by scripts/generate-settings-meta.py — DO NOT EDIT.
//
// Run `pnpm generate:settings-meta` after a firmware schema change.
// Source: components/settings/include/settings/schema.hpp::kFields in
// the btclock firmware repo.

import * as v from 'valibot';

export type SettingsFieldKind = 'string' | 'number' | 'boolean';

export interface SettingsFieldMeta {
\tkey: string;
\tkind: SettingsFieldKind;
\tbootOnly: boolean;
\tminValue: number;
\tmaxValue: number;
\tdefaultBool: boolean;
\tdefaultInt: number;
\tdefaultStr: string;
}

"""

SCHEMA_PREAMBLE = """\
/**
 * Per-field Valibot schemas mirroring kFields. Numeric fields carry their
 * min/max bounds; strings/booleans are primitive validators. Compose into
 * the API settings schema (see $lib/api/schemas).
 *
 * kField keys are flat NVS prefs keys. The HTTP /api/settings JSON
 * reshapes a few of them — `actCurrencies` ships as string[], the
 * `dnd*` keys are nested under `dnd` — so callers must drop or override
 * those before using this record verbatim.
 */
"""


def field_schema_expr(f: dict) -> str:
    kind = f["kind"]
    if kind == "boolean":
        return "v.boolean()"
    if kind == "string":
        return "v.string()"
    if kind == "number":
        if f["minValue"] == 0 and f["maxValue"] == 0:
            return "v.number()"
        return (
            f"v.pipe(v.number(), v.minValue({f['minValue']}), v.maxValue({f['maxValue']}))"
        )
    return "v.unknown()"


def emit(fields: list[dict]) -> str:
    out = [HEADER, "export const settingsFieldMeta: readonly SettingsFieldMeta[] = ["]
    for f in fields:
        out.append(
            "\t{ "
            + f"key: '{f['key']}', "
            + f"kind: '{f['kind']}', "
            + f"bootOnly: {'true' if f['bootOnly'] else 'false'}, "
            + f"minValue: {f['minValue']}, "
            + f"maxValue: {f['maxValue']}, "
            + f"defaultBool: {'true' if f['defaultBool'] else 'false'}, "
            + f"defaultInt: {f['defaultInt']}, "
            + f"defaultStr: {f['defaultStr']!r}"
            + " },"
        )
    out.append("];\n")
    out.append(
        "export const settingsFieldsByKey: Readonly<Record<string, SettingsFieldMeta>> = "
        "Object.freeze(\n"
        "\tObject.fromEntries(settingsFieldMeta.map((f) => [f.key, f]))\n);\n"
    )
    out.append(
        "export const isBootOnly = (key: string): boolean =>\n"
        "\tsettingsFieldsByKey[key]?.bootOnly === true;\n"
    )
    out.append(SCHEMA_PREAMBLE + "export const settingsFieldSchemas = {")
    for f in fields:
        out.append(f"\t{f['key']}: {field_schema_expr(f)},")
    out.append("} as const;\n")
    return "\n".join(out)


# ---- Driver ----------------------------------------------------------------


def default_firmware_root(webui_root: Path) -> Path:
    parent = webui_root.parent
    schema_rel = Path("components/settings/include/settings/schema.hpp")
    if (parent / schema_rel).is_file():
        return parent
    sibling = parent / "btclock_v4"
    if (sibling / schema_rel).is_file():
        return sibling
    return sibling


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    here = Path(__file__).resolve().parent.parent
    parser.add_argument(
        "--firmware",
        type=Path,
        default=default_firmware_root(here),
        help="Firmware repo root (directory containing components/). Auto-detected when omitted.",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=here / "src" / "lib" / "types" / "settings.generated.ts",
    )
    args = parser.parse_args()

    schema_h = args.firmware / "components/settings/include/settings/schema.hpp"
    keys_h = args.firmware / "components/settings/include/settings/pref_keys.hpp"
    if not schema_h.is_file():
        sys.exit(f"schema.hpp not found at {schema_h}; pass --firmware <path>")
    if not keys_h.is_file():
        sys.exit(f"pref_keys.hpp not found at {keys_h}")

    key_map = parse_pref_keys(keys_h.read_text())
    fields = sorted(parse_kfields(schema_h.read_text(), key_map), key=lambda f: f["key"])
    if not fields:
        sys.exit("Parsed zero fields — regex drift, schema.hpp format changed.")

    args.out.write_text(emit(fields))
    out_label = args.out
    try:
        out_label = args.out.resolve().relative_to(here)
    except ValueError:
        # --out points outside the repo (CI's check:settings-meta writes to
        # /tmp). Fall back to the absolute path so the message stays useful.
        pass
    print(f"wrote {len(fields)} fields → {out_label}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
