// AUTO-GENERATED by scripts/generate-settings-meta.py — DO NOT EDIT.
//
// Run `pnpm generate:settings-meta` after a firmware schema change.
// Source: components/settings/include/settings/schema.hpp::kFields in
// the btclock firmware repo.

import * as v from 'valibot';

export type SettingsFieldKind = 'string' | 'number' | 'boolean';

export interface SettingsFieldMeta {
	key: string;
	kind: SettingsFieldKind;
	bootOnly: boolean;
	minValue: number;
	maxValue: number;
	defaultBool: boolean;
	defaultInt: number;
	defaultStr: string;
}

export const settingsFieldMeta: readonly SettingsFieldMeta[] = [
	{
		key: 'actCurrencies',
		kind: 'string',
		bootOnly: false,
		minValue: 0,
		maxValue: 0,
		defaultBool: false,
		defaultInt: 0,
		defaultStr: 'USD,EUR,JPY'
	},
	{
		key: 'bitaxeEnabled',
		kind: 'boolean',
		bootOnly: false,
		minValue: 0,
		maxValue: 0,
		defaultBool: false,
		defaultInt: 0,
		defaultStr: ''
	},
	{
		key: 'bitaxeHostname',
		kind: 'string',
		bootOnly: false,
		minValue: 0,
		maxValue: 0,
		defaultBool: false,
		defaultInt: 0,
		defaultStr: 'bitaxe1'
	},
	{
		key: 'bitaxePollSec',
		kind: 'number',
		bootOnly: false,
		minValue: 5,
		maxValue: 300,
		defaultBool: false,
		defaultInt: 10,
		defaultStr: ''
	},
	{
		key: 'blockFeeDec',
		kind: 'boolean',
		bootOnly: false,
		minValue: 0,
		maxValue: 0,
		defaultBool: true,
		defaultInt: 0,
		defaultStr: ''
	},
	{
		key: 'blockFlashColor',
		kind: 'number',
		bootOnly: false,
		minValue: 0,
		maxValue: 16777215,
		defaultBool: false,
		defaultInt: 14697216,
		defaultStr: ''
	},
	{
		key: 'ceDisableSSL',
		kind: 'boolean',
		bootOnly: true,
		minValue: 0,
		maxValue: 0,
		defaultBool: false,
		defaultInt: 0,
		defaultStr: ''
	},
	{
		key: 'ceEndpoint',
		kind: 'string',
		bootOnly: true,
		minValue: 0,
		maxValue: 0,
		defaultBool: false,
		defaultInt: 0,
		defaultStr: 'ws-staging.btclock.dev'
	},
	{
		key: 'dataSource',
		kind: 'number',
		bootOnly: true,
		minValue: 0,
		maxValue: 3,
		defaultBool: false,
		defaultInt: 0,
		defaultStr: ''
	},
	{
		key: 'decimalShareDot',
		kind: 'boolean',
		bootOnly: false,
		minValue: 0,
		maxValue: 0,
		defaultBool: false,
		defaultInt: 0,
		defaultStr: ''
	},
	{
		key: 'digitFontPx',
		kind: 'number',
		bootOnly: false,
		minValue: 80,
		maxValue: 220,
		defaultBool: false,
		defaultInt: 180,
		defaultStr: ''
	},
	{
		key: 'disableLeds',
		kind: 'boolean',
		bootOnly: false,
		minValue: 0,
		maxValue: 0,
		defaultBool: false,
		defaultInt: 0,
		defaultStr: ''
	},
	{
		key: 'dndEnabled',
		kind: 'boolean',
		bootOnly: false,
		minValue: 0,
		maxValue: 0,
		defaultBool: false,
		defaultInt: 0,
		defaultStr: ''
	},
	{
		key: 'dndEndHour',
		kind: 'number',
		bootOnly: false,
		minValue: 0,
		maxValue: 23,
		defaultBool: false,
		defaultInt: 7,
		defaultStr: ''
	},
	{
		key: 'dndEndMin',
		kind: 'number',
		bootOnly: false,
		minValue: 0,
		maxValue: 59,
		defaultBool: false,
		defaultInt: 0,
		defaultStr: ''
	},
	{
		key: 'dndStartHour',
		kind: 'number',
		bootOnly: false,
		minValue: 0,
		maxValue: 23,
		defaultBool: false,
		defaultInt: 22,
		defaultStr: ''
	},
	{
		key: 'dndStartMin',
		kind: 'number',
		bootOnly: false,
		minValue: 0,
		maxValue: 59,
		defaultBool: false,
		defaultInt: 0,
		defaultStr: ''
	},
	{
		key: 'dndTimeEnabled',
		kind: 'boolean',
		bootOnly: false,
		minValue: 0,
		maxValue: 0,
		defaultBool: false,
		defaultInt: 0,
		defaultStr: ''
	},
	{
		key: 'enableDebugLog',
		kind: 'boolean',
		bootOnly: true,
		minValue: 0,
		maxValue: 0,
		defaultBool: false,
		defaultInt: 0,
		defaultStr: ''
	},
	{
		key: 'flAlwaysOn',
		kind: 'boolean',
		bootOnly: false,
		minValue: 0,
		maxValue: 0,
		defaultBool: true,
		defaultInt: 0,
		defaultStr: ''
	},
	{
		key: 'flDisable',
		kind: 'boolean',
		bootOnly: false,
		minValue: 0,
		maxValue: 0,
		defaultBool: false,
		defaultInt: 0,
		defaultStr: ''
	},
	{
		key: 'flEffectDelay',
		kind: 'number',
		bootOnly: false,
		minValue: 0,
		maxValue: 1000,
		defaultBool: false,
		defaultInt: 15,
		defaultStr: ''
	},
	{
		key: 'flFlashOnUpd',
		kind: 'boolean',
		bootOnly: false,
		minValue: 0,
		maxValue: 0,
		defaultBool: true,
		defaultInt: 0,
		defaultStr: ''
	},
	{
		key: 'flFlashOnZap',
		kind: 'boolean',
		bootOnly: false,
		minValue: 0,
		maxValue: 0,
		defaultBool: true,
		defaultInt: 0,
		defaultStr: ''
	},
	{
		key: 'flMaxBrightness',
		kind: 'number',
		bootOnly: false,
		minValue: 0,
		maxValue: 65535,
		defaultBool: false,
		defaultInt: 2048,
		defaultStr: ''
	},
	{
		key: 'flOffWhenDark',
		kind: 'boolean',
		bootOnly: false,
		minValue: 0,
		maxValue: 0,
		defaultBool: true,
		defaultInt: 0,
		defaultStr: ''
	},
	{
		key: 'fontName',
		kind: 'string',
		bootOnly: false,
		minValue: 0,
		maxValue: 0,
		defaultBool: false,
		defaultInt: 0,
		defaultStr: 'antonio'
	},
	{
		key: 'fullRefreshMin',
		kind: 'number',
		bootOnly: false,
		minValue: 0,
		maxValue: 1440,
		defaultBool: false,
		defaultInt: 60,
		defaultStr: ''
	},
	{
		key: 'gitReleaseUrl',
		kind: 'string',
		bootOnly: false,
		minValue: 0,
		maxValue: 0,
		defaultBool: false,
		defaultInt: 0,
		defaultStr: 'https://git.btclock.dev/api/v1/repos/btclock/btclock_v4/releases/latest'
	},
	{
		key: 'hideLeadZero',
		kind: 'boolean',
		bootOnly: false,
		minValue: 0,
		maxValue: 0,
		defaultBool: false,
		defaultInt: 0,
		defaultStr: ''
	},
	{
		key: 'hostnamePrefix',
		kind: 'string',
		bootOnly: false,
		minValue: 0,
		maxValue: 0,
		defaultBool: false,
		defaultInt: 0,
		defaultStr: 'btclock'
	},
	{
		key: 'httpAuthEnabled',
		kind: 'boolean',
		bootOnly: true,
		minValue: 0,
		maxValue: 0,
		defaultBool: false,
		defaultInt: 0,
		defaultStr: ''
	},
	{
		key: 'httpAuthPass',
		kind: 'string',
		bootOnly: true,
		minValue: 0,
		maxValue: 0,
		defaultBool: false,
		defaultInt: 0,
		defaultStr: ''
	},
	{
		key: 'httpAuthUser',
		kind: 'string',
		bootOnly: true,
		minValue: 0,
		maxValue: 0,
		defaultBool: false,
		defaultInt: 0,
		defaultStr: 'btclock'
	},
	{
		key: 'inverseButtons',
		kind: 'boolean',
		bootOnly: false,
		minValue: 0,
		maxValue: 0,
		defaultBool: false,
		defaultInt: 0,
		defaultStr: ''
	},
	{
		key: 'invertedColor',
		kind: 'boolean',
		bootOnly: false,
		minValue: 0,
		maxValue: 0,
		defaultBool: false,
		defaultInt: 0,
		defaultStr: ''
	},
	{
		key: 'ledBrightness',
		kind: 'number',
		bootOnly: false,
		minValue: 0,
		maxValue: 255,
		defaultBool: false,
		defaultInt: 128,
		defaultStr: ''
	},
	{
		key: 'ledFlashOnUpd',
		kind: 'boolean',
		bootOnly: false,
		minValue: 0,
		maxValue: 0,
		defaultBool: true,
		defaultInt: 0,
		defaultStr: ''
	},
	{
		key: 'ledFlashOnZap',
		kind: 'boolean',
		bootOnly: false,
		minValue: 0,
		maxValue: 0,
		defaultBool: true,
		defaultInt: 0,
		defaultStr: ''
	},
	{
		key: 'ledTestOnPower',
		kind: 'boolean',
		bootOnly: false,
		minValue: 0,
		maxValue: 0,
		defaultBool: true,
		defaultInt: 0,
		defaultStr: ''
	},
	{
		key: 'localPoolHost',
		kind: 'string',
		bootOnly: true,
		minValue: 0,
		maxValue: 0,
		defaultBool: false,
		defaultInt: 0,
		defaultStr: 'umbrel.local:2019'
	},
	{
		key: 'luxLightToggle',
		kind: 'number',
		bootOnly: false,
		minValue: 0,
		maxValue: 65535,
		defaultBool: false,
		defaultInt: 128,
		defaultStr: ''
	},
	{
		key: 'mcapBigChar',
		kind: 'boolean',
		bootOnly: false,
		minValue: 0,
		maxValue: 0,
		defaultBool: true,
		defaultInt: 0,
		defaultStr: ''
	},
	{
		key: 'mdnsEnabled',
		kind: 'boolean',
		bootOnly: false,
		minValue: 0,
		maxValue: 0,
		defaultBool: true,
		defaultInt: 0,
		defaultStr: ''
	},
	{
		key: 'mempoolInstance',
		kind: 'string',
		bootOnly: true,
		minValue: 0,
		maxValue: 0,
		defaultBool: false,
		defaultInt: 0,
		defaultStr: 'mempool.space'
	},
	{
		key: 'mempoolSecure',
		kind: 'boolean',
		bootOnly: true,
		minValue: 0,
		maxValue: 0,
		defaultBool: true,
		defaultInt: 0,
		defaultStr: ''
	},
	{
		key: 'minSecPriceUpd',
		kind: 'number',
		bootOnly: false,
		minValue: 1,
		maxValue: 3600,
		defaultBool: false,
		defaultInt: 30,
		defaultStr: ''
	},
	{
		key: 'miningPoolName',
		kind: 'string',
		bootOnly: false,
		minValue: 0,
		maxValue: 0,
		defaultBool: false,
		defaultInt: 0,
		defaultStr: 'noderunners'
	},
	{
		key: 'miningPoolStats',
		kind: 'boolean',
		bootOnly: false,
		minValue: 0,
		maxValue: 0,
		defaultBool: false,
		defaultInt: 0,
		defaultStr: ''
	},
	{
		key: 'miningPoolUser',
		kind: 'string',
		bootOnly: false,
		minValue: 0,
		maxValue: 0,
		defaultBool: false,
		defaultInt: 0,
		defaultStr: '38Qkkei3SuF1Eo45BaYmRHUneRD54yyTFy'
	},
	{
		key: 'mowMode',
		kind: 'boolean',
		bootOnly: false,
		minValue: 0,
		maxValue: 0,
		defaultBool: false,
		defaultInt: 0,
		defaultStr: ''
	},
	{
		key: 'nostrPubKey',
		kind: 'string',
		bootOnly: true,
		minValue: 0,
		maxValue: 0,
		defaultBool: false,
		defaultInt: 0,
		defaultStr: '642317135fd4c4205323b9dea8af3270657e62d51dc31a657c0ec8aab31c6288'
	},
	{
		key: 'nostrRelay',
		kind: 'string',
		bootOnly: true,
		minValue: 0,
		maxValue: 0,
		defaultBool: false,
		defaultInt: 0,
		defaultStr: 'wss://relay.primal.net'
	},
	{
		key: 'nostrZapNotify',
		kind: 'boolean',
		bootOnly: false,
		minValue: 0,
		maxValue: 0,
		defaultBool: false,
		defaultInt: 0,
		defaultStr: ''
	},
	{
		key: 'nostrZapPubkey',
		kind: 'string',
		bootOnly: false,
		minValue: 0,
		maxValue: 0,
		defaultBool: false,
		defaultInt: 0,
		defaultStr: 'b5127a08cf33616274800a4387881a9f98e04b9c37116e92de5250498635c422'
	},
	{
		key: 'otaEnabled',
		kind: 'boolean',
		bootOnly: true,
		minValue: 0,
		maxValue: 0,
		defaultBool: true,
		defaultInt: 0,
		defaultStr: ''
	},
	{
		key: 'otaPass',
		kind: 'string',
		bootOnly: true,
		minValue: 0,
		maxValue: 0,
		defaultBool: false,
		defaultInt: 0,
		defaultStr: ''
	},
	{
		key: 'poolGlobalStats',
		kind: 'boolean',
		bootOnly: false,
		minValue: 0,
		maxValue: 0,
		defaultBool: true,
		defaultInt: 0,
		defaultStr: ''
	},
	{
		key: 'poolLogosUrl',
		kind: 'string',
		bootOnly: false,
		minValue: 0,
		maxValue: 0,
		defaultBool: false,
		defaultInt: 0,
		defaultStr: 'https://git.btclock.dev/btclock/mining-pool-logos/raw/branch/main'
	},
	{
		key: 'poolPollSec',
		kind: 'number',
		bootOnly: false,
		minValue: 10,
		maxValue: 3600,
		defaultBool: false,
		defaultInt: 60,
		defaultStr: ''
	},
	{
		key: 'poolWorker',
		kind: 'string',
		bootOnly: false,
		minValue: 0,
		maxValue: 0,
		defaultBool: false,
		defaultInt: 0,
		defaultStr: ''
	},
	{
		key: 'refrScrnChange',
		kind: 'boolean',
		bootOnly: false,
		minValue: 0,
		maxValue: 0,
		defaultBool: false,
		defaultInt: 0,
		defaultStr: ''
	},
	{
		key: 'satsVariant',
		kind: 'number',
		bootOnly: false,
		minValue: 0,
		maxValue: 15,
		defaultBool: false,
		defaultInt: 7,
		defaultStr: ''
	},
	{
		key: 'scrnRestoreZap',
		kind: 'boolean',
		bootOnly: false,
		minValue: 0,
		maxValue: 0,
		defaultBool: true,
		defaultInt: 0,
		defaultStr: ''
	},
	{
		key: 'stealFocus',
		kind: 'boolean',
		bootOnly: false,
		minValue: 0,
		maxValue: 0,
		defaultBool: true,
		defaultInt: 0,
		defaultStr: ''
	},
	{
		key: 'suffixPrice',
		kind: 'boolean',
		bootOnly: false,
		minValue: 0,
		maxValue: 0,
		defaultBool: false,
		defaultInt: 0,
		defaultStr: ''
	},
	{
		key: 'supplyPercent',
		kind: 'boolean',
		bootOnly: false,
		minValue: 0,
		maxValue: 0,
		defaultBool: false,
		defaultInt: 0,
		defaultStr: ''
	},
	{
		key: 'tzString',
		kind: 'string',
		bootOnly: false,
		minValue: 0,
		maxValue: 0,
		defaultBool: false,
		defaultInt: 0,
		defaultStr: 'Europe/Amsterdam'
	},
	{
		key: 'useBlkCountdown',
		kind: 'boolean',
		bootOnly: false,
		minValue: 0,
		maxValue: 0,
		defaultBool: true,
		defaultInt: 0,
		defaultStr: ''
	},
	{
		key: 'useMscwTime',
		kind: 'boolean',
		bootOnly: false,
		minValue: 0,
		maxValue: 0,
		defaultBool: true,
		defaultInt: 0,
		defaultStr: ''
	},
	{
		key: 'useSatsSymbol',
		kind: 'boolean',
		bootOnly: false,
		minValue: 0,
		maxValue: 0,
		defaultBool: false,
		defaultInt: 0,
		defaultStr: ''
	},
	{
		key: 'verticalDesc',
		kind: 'boolean',
		bootOnly: false,
		minValue: 0,
		maxValue: 0,
		defaultBool: true,
		defaultInt: 0,
		defaultStr: ''
	},
	{
		key: 'wifiRebootMin',
		kind: 'number',
		bootOnly: false,
		minValue: 0,
		maxValue: 120,
		defaultBool: false,
		defaultInt: 10,
		defaultStr: ''
	},
	{
		key: 'wpTimeout',
		kind: 'number',
		bootOnly: true,
		minValue: 0,
		maxValue: 3600,
		defaultBool: false,
		defaultInt: 900,
		defaultStr: ''
	}
];

export const settingsFieldsByKey: Readonly<Record<string, SettingsFieldMeta>> = Object.freeze(
	Object.fromEntries(settingsFieldMeta.map((f) => [f.key, f]))
);

export const isBootOnly = (key: string): boolean => settingsFieldsByKey[key]?.bootOnly === true;

/**
 * Per-field Valibot schemas mirroring kFields. Numeric fields carry their
 * min/max bounds; strings/booleans are primitive validators. Compose into
 * the API settings schema (see $lib/api/schemas).
 *
 * kField keys are flat NVS prefs keys. The HTTP /api/settings JSON
 * reshapes a few of them — `actCurrencies` ships as string[], the
 * `dnd*` keys are nested under `dnd` — so callers must drop or override
 * those before using this record verbatim.
 */
export const settingsFieldSchemas = {
	actCurrencies: v.string(),
	bitaxeEnabled: v.boolean(),
	bitaxeHostname: v.string(),
	bitaxePollSec: v.pipe(v.number(), v.minValue(5), v.maxValue(300)),
	blockFeeDec: v.boolean(),
	blockFlashColor: v.pipe(v.number(), v.minValue(0), v.maxValue(16777215)),
	ceDisableSSL: v.boolean(),
	ceEndpoint: v.string(),
	dataSource: v.pipe(v.number(), v.minValue(0), v.maxValue(3)),
	decimalShareDot: v.boolean(),
	digitFontPx: v.pipe(v.number(), v.minValue(80), v.maxValue(220)),
	disableLeds: v.boolean(),
	dndEnabled: v.boolean(),
	dndEndHour: v.pipe(v.number(), v.minValue(0), v.maxValue(23)),
	dndEndMin: v.pipe(v.number(), v.minValue(0), v.maxValue(59)),
	dndStartHour: v.pipe(v.number(), v.minValue(0), v.maxValue(23)),
	dndStartMin: v.pipe(v.number(), v.minValue(0), v.maxValue(59)),
	dndTimeEnabled: v.boolean(),
	enableDebugLog: v.boolean(),
	flAlwaysOn: v.boolean(),
	flDisable: v.boolean(),
	flEffectDelay: v.pipe(v.number(), v.minValue(0), v.maxValue(1000)),
	flFlashOnUpd: v.boolean(),
	flFlashOnZap: v.boolean(),
	flMaxBrightness: v.pipe(v.number(), v.minValue(0), v.maxValue(65535)),
	flOffWhenDark: v.boolean(),
	fontName: v.string(),
	fullRefreshMin: v.pipe(v.number(), v.minValue(0), v.maxValue(1440)),
	gitReleaseUrl: v.string(),
	hideLeadZero: v.boolean(),
	hostnamePrefix: v.string(),
	httpAuthEnabled: v.boolean(),
	httpAuthPass: v.string(),
	httpAuthUser: v.string(),
	inverseButtons: v.boolean(),
	invertedColor: v.boolean(),
	ledBrightness: v.pipe(v.number(), v.minValue(0), v.maxValue(255)),
	ledFlashOnUpd: v.boolean(),
	ledFlashOnZap: v.boolean(),
	ledTestOnPower: v.boolean(),
	localPoolHost: v.string(),
	luxLightToggle: v.pipe(v.number(), v.minValue(0), v.maxValue(65535)),
	mcapBigChar: v.boolean(),
	mdnsEnabled: v.boolean(),
	mempoolInstance: v.string(),
	mempoolSecure: v.boolean(),
	minSecPriceUpd: v.pipe(v.number(), v.minValue(1), v.maxValue(3600)),
	miningPoolName: v.string(),
	miningPoolStats: v.boolean(),
	miningPoolUser: v.string(),
	mowMode: v.boolean(),
	nostrPubKey: v.string(),
	nostrRelay: v.string(),
	nostrZapNotify: v.boolean(),
	nostrZapPubkey: v.string(),
	otaEnabled: v.boolean(),
	otaPass: v.string(),
	poolGlobalStats: v.boolean(),
	poolLogosUrl: v.string(),
	poolPollSec: v.pipe(v.number(), v.minValue(10), v.maxValue(3600)),
	poolWorker: v.string(),
	refrScrnChange: v.boolean(),
	satsVariant: v.pipe(v.number(), v.minValue(0), v.maxValue(15)),
	scrnRestoreZap: v.boolean(),
	stealFocus: v.boolean(),
	suffixPrice: v.boolean(),
	supplyPercent: v.boolean(),
	tzString: v.string(),
	useBlkCountdown: v.boolean(),
	useMscwTime: v.boolean(),
	useSatsSymbol: v.boolean(),
	verticalDesc: v.boolean(),
	wifiRebootMin: v.pipe(v.number(), v.minValue(0), v.maxValue(120)),
	wpTimeout: v.pipe(v.number(), v.minValue(0), v.maxValue(3600))
} as const;
